Local environment page
ethereum/ethereum-org-fork pull request #128
Opened 2023-11-16 17:28 UTC by corwintines

## Description

- Implements /developers/local-environment page

2023-11-30 14:40 UTC, pettinarip requested changes
The main image is bigger than the one in prod and makes the layout a bit different
pr:
![image](https://github.com/ethereum/ethereum-org-fork/assets/468158/d92f5a68-3d33-4ee9-be8d-6a8fd8a44f43)

prod:
![image](https://github.com/ethereum/ethereum-org-fork/assets/468158/a0eb5fd1-7c00-474c-830b-715a68f1aca1)

=====
The github stars component is full width vs the prod version that is aligned to the right:

pr:
![image](https://github.com/ethereum/ethereum-org-fork/assets/468158/9ba07f7f-32dc-40d5-9a33-22903348f12b)

prod:
![image](https://github.com/ethereum/ethereum-org-fork/assets/468158/76a77ab5-4fa0-409f-ae30-187eda51b2a2)

2023-11-30 14:40 UTC, pettinarip commented on src/lib/api/ghRepoData.ts
> +import "dotenv/config"
Why do we need to do this? I think it shouldn't be needed since NextJS is loading the env vars already for you.

2023-11-30 14:40 UTC, pettinarip commented on src/pages/developers/local-environment.tsx
> +interface IFramework {
Should we put this under `interfaces.ts`?

2023-11-30 14:40 UTC, pettinarip commented on src/pages/developers/local-environment.tsx
> +export const getStaticProps: GetStaticProps = async (
Lets use the `satisfies GetStaticProps<Props>` form

2023-11-30 14:40 UTC, pettinarip commented on src/pages/developers/local-environment.tsx
> +      frameworksList,
Same as the other PRs, we need to export the `lastDeployDate` as well.

2023-11-30 14:40 UTC, pettinarip commented on src/pages/developers/local-environment.tsx
> +  let frameworksList: Array<IFramework> = [
We could place this array outside of the `getStaticProps` hook to improve readability.

2023-11-30 14:40 UTC, pettinarip commented on src/pages/developers/local-environment.tsx
> +  // TODO: fetch github repo data
Aren't we fetching this data in this PR? not sure if I understand what is left to do.

2023-11-30 14:40 UTC, pettinarip commented on src/pages/developers/local-environment.tsx
> +const LocalEnvironmentPage = ({ frameworksList }) => {
Lets declare the types for this page by doing:

```suggestion
const LocalEnvironmentPage = ({ frameworksList }: InferGetStaticPropsType<typeof getStaticProps>)) => {
```

2023-11-30 14:40 UTC, pettinarip commented on src/pages/developers/local-environment.tsx
> +        title={t("page-developers-local-environment:page-local-environment-setup-meta-title")}
tip: not 100% sure but I think that when you need to use the first namespace declared in the `useTranslation`, you don't need to specify the namespace in the `t` function.

https://react.i18next.com/latest/usetranslation-hook#loading-namespaces
```
const { t, i18n } = useTranslation(['ns1', 'ns2', 'ns3']);
t('key'); // will be looked up from namespace ns1
```

2023-11-30 19:35 UTC, corwintines commented on src/lib/api/ghRepoData.ts
> +import "dotenv/config"
Ah my mistake. Removing.

2023-11-30 19:46 UTC, corwintines commented on src/pages/developers/local-environment.tsx
> +interface IFramework {
Sure. Its only used here, but happy to move.

2023-12-06 14:58 UTC, wackerow approved these changes
Still getting some hydration warnings, but pushed a commit to clear the merge conflicts which fixed the build issues failing at type checking.

The above issues noted all appear to be resolved; page appears the same to me as production.

2023-12-06 18:44 UTC, wackerow commented
Patched react-i18next -> next-i18next instances, updated with dev again... preview building now, passed locally

2023-12-07 11:45 UTC, pettinarip commented on src/lib/api/ghRepoData.ts
> +export const getLocalEnvironmentFrameworkData = async () => {
Good idea moving this here 👍🏼

2023-12-07 11:45 UTC, pettinarip commented on src/components/ProductCard.tsx
I see that the stars component is filling the full available the space + an orange underline
![image](https://github.com/ethereum/ethereum-org-fork/assets/468158/7bd956c7-6207-4ec1-8ffd-06021afdfaf7)

while in prod it is shown like this
![image](https://github.com/ethereum/ethereum-org-fork/assets/468158/bd4e43fc-10e9-4e18-9986-b9ab3ce7c26a)

2023-12-07 11:45 UTC, pettinarip commented on src/lib/types.ts
> +import { type Options, toc } from "mdast-util-toc"
Revert this? it doesn't seem that we are using `toc`
```suggestion
import type { Options } from "mdast-util-toc"
```

2023-12-07 14:13 UTC, wackerow commented on src/components/ProductCard.tsx
@pettinarip Can you check your cache? I'm not getting this
[PR preview](https://deploy-preview-128--ethereum-org-fork.netlify.app/en/developers/local-environment):
<img width="1473" alt="image" src="https://github.com/ethereum/ethereum-org-fork/assets/54227730/727b046c-5f90-41b7-a060-db383d247816">

2023-12-07 14:28 UTC, pettinarip commented on src/components/ProductCard.tsx
Ok! after investigating, I was using a pretty outdated Brave version. I see it good now in FF, Chrome, and Brave! 🎉

2023-12-07 14:30 UTC, pettinarip approved these changes
Nice job @corwintines, thanks!

2023-12-07 15:18 UTC, merged