Add sitemap, robots and manifest
ethereum/ethereum-org-fork pull request #155
Opened 2023-11-29 22:11 UTC by wackerow

## Description
- Adds `next/sitemap` package and `next-sitemap.config.js` config file
- Config also includes generation of `public/robots.txt` file (added to `.gitignore`)
- Adds `public/manifest.json` with necessary image assets

## Related Issue
https://www.notion.so/efdn/Add-robots-txt-and-sitemap-dbc564c8b7f240a1b5fd81187856bb54?pvs=4

2023-12-01 13:48 UTC, pettinarip reviewed
Looks good to me @wackerow 

Comparing it with the prod version, I see that we are changing the `changefreq` to `daily` and the `priority` to `0.5`. In prod we were using `monthly` & `0.7`. Not sure if this might have a negative impact or not, just wanted to call it out.

cc @nhsz not sure if you have any preference here

2023-12-01 13:48 UTC, pettinarip commented on next-sitemap.config.js
> +  generateRobotsTxt: true,
I see that we are indexing the 404 pages
https://deploy-preview-155--ethereum-org-fork.netlify.app/sitemap-0.xml

Maybe we could exclude those from the sitemap generation by using the `exclude` option.

2023-12-01 13:51 UTC, wackerow commented on next-sitemap.config.js
> +  generateRobotsTxt: true,
Yeah good call, looks like we're doing that on the Gatsby side
<img width="534" alt="image" src="https://github.com/ethereum/ethereum-org-fork/assets/54227730/cfdfe33b-b3fd-4015-966d-c857fecdded8">

Will update

2023-12-01 14:24 UTC, wackerow commented
> Comparing it with the prod version, I see that we are changing the changefreq to daily and the priority to 0.5. In prod we were using monthly & 0.7. Not sure if this might have a negative impact or not, just wanted to call it out.

Looks like in prod we're using `weekly`/`0.7` for _English_, and `monthly`/`0.5` for _non-English_. This plugin defaults to `daily`/`0.7`... I'll look into using a transform to add a conditional here to match parity with Gatsby site.

2023-12-03 11:51 UTC, pettinarip requested changes

2023-12-03 11:51 UTC, pettinarip commented on next-sitemap.config.js
> +  generateRobotsTxt: true,
@wackerow I still see some other 404 cases, like the ones for each lang
![image](https://github.com/ethereum/ethereum-org-fork/assets/468158/88cc56ce-360a-4a7c-bce3-32755eb1e6a2)

2023-12-05 10:39 UTC, pettinarip commented on next-sitemap.config.js
> +  generateRobotsTxt: true,
Fixed.

2023-12-05 10:40 UTC, pettinarip approved these changes

2023-12-05 14:16 UTC, wackerow commented
Another option here that I left off was the `trailingSlash`... This has not been added to our `tsconfig` although we may want to consider; the canonical repo used this and if we plan to deploy a static export to IPFS I think this will be required. Doesn't have to block this PR, can discuss more.

2023-12-05 14:32 UTC, nhsz approved these changes
lgtm

2023-12-05 14:32 UTC, merged