/developers/tutorials page migration
ethereum/ethereum-org-fork pull request #159
Opened 2023-11-30 17:58 UTC by corwintines

## Description

- Implement /developers/tutorials page
- Implement internal tutorials crawler im md.ts
- Implement tutorial utils

2023-12-03 12:34 UTC, pettinarip requested changes
Nice @corwintines, left a few small change requests

2023-12-03 12:34 UTC, pettinarip commented on src/pages/developers/tutorials.tsx
> +export const getStaticProps: GetStaticProps = async (
Use the `satisfies GetStaticProps` form
```suggestion
export const getStaticProps = async (
```

2023-12-03 12:34 UTC, pettinarip commented on src/pages/developers/tutorials.tsx
> +const TutorialPage = ({ internalTutorials, locale }) => {
```suggestion
const TutorialPage = ({ internalTutorials, locale }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
```

2023-12-03 12:34 UTC, pettinarip commented on src/pages/developers/tutorials.tsx
> +      locale,
We also need to export the `lastDeployDate`.
![image](https://github.com/ethereum/ethereum-org-fork/assets/468158/e9b4affd-7a74-4ef6-87d6-707cf9cb55db)

2023-12-03 12:34 UTC, pettinarip commented on src/pages/developers/tutorials.tsx
> +                    <Translation id="page-tutorial-read-time" />
We need to specify the namespace in this case 
![image](https://github.com/ethereum/ethereum-org-fork/assets/468158/aeeea0cd-5726-4482-abca-9289cb4dd217)

2023-12-03 12:34 UTC, pettinarip commented on src/pages/developers/tutorials.tsx
> +                      <Translation id="page-tutorial-external-link" />
Same here

2023-12-07 14:43 UTC, wackerow approved these changes
LGTM after recent commits! Nice job @corwintines!

2023-12-08 10:45 UTC, pettinarip approved these changes
LGTM

Pushing a new commit to improve the typing on the getstaticprops hook.

2023-12-08 10:45 UTC, pettinarip commented on src/pages/developers/tutorials.tsx
> +}) satisfies GetStaticProps<SSRConfig>
We are missing the other props that we are returning here. This will help `InferGetServerSidePropsType` to infer the correct prop types.

We can do:
```ts
type Props = SSRConfig & {
  internalTutorials
  ...
}

satisfies GetStaticProps<Props>
```

2023-12-11 10:53 UTC, merged