Feedback widget
ethereum/ethereum-org-fork pull request #161
Opened 2023-12-01 06:14 UTC by wackerow

## Description
- Add `focus-trap-react` package
- Migrate `useKeyPress` hook
- Migrate `useOnClickOutside` hook
- Update `FeedbackWidget` component
- Implement `FeedbackWidget` inside `RootLayout`

Cherry-picks bc400d674 from #152, implementing `useSurvey` hook

## Related Issue
https://www.notion.so/efdn/Add-Feedback-widget-c99e6d8e04b0425ca6769c7ddf63ba7d?pvs=4

2023-12-01 11:37 UTC, minimalsm commented on package.json
> +    "focus-trap-react": "^10.2.3",
Where is this being used?

2023-12-01 12:59 UTC, wackerow commented on package.json
> +    "focus-trap-react": "^10.2.3",
@minimalsm 
https://github.com/ethereum/ethereum-org-fork/blob/6c16af52680bc7636c8b14a1c1fef1baf7c3fdb7/src/components/FeedbackWidget.tsx#L2
https://github.com/ethereum/ethereum-org-fork/blob/6c16af52680bc7636c8b14a1c1fef1baf7c3fdb7/src/components/FeedbackWidget.tsx#L186

or in canonical:
https://github.com/ethereum/ethereum-org-website/blob/9163e6b7a3063c4ccec282c63b39685b60abe667/src/components/FeedbackWidget.tsx#L189

2023-12-05 12:03 UTC, pettinarip requested changes
I see this translation without parsing in the FeedbackCard. This happens when only the `t` function is used. For rich text content, we have to parse the content with `htmr` which is implemented in the `Translation` component.

![image](https://github.com/ethereum/ethereum-org-fork/assets/468158/75ce876f-eae1-4a66-b8c0-0fe5fbeaf3cf)

2023-12-05 12:13 UTC, pettinarip approved these changes
Nice job @wackerow, looks great.

I've pushed a commit to fix the not parsed translation and some conflicts with dev.

2023-12-05 20:17 UTC, nhsz approved these changes
LGTM

2023-12-05 20:17 UTC, merged