Fix locales with 4 words like `pt-br`
ethereum/ethereum-org-fork pull request #252
Opened 2023-12-21 16:45 UTC by pettinarip

## Description

## Related Issue

2023-12-21 18:31 UTC, minimalsm approved these changes

2024-01-03 19:01 UTC, corwintines approved these changes

2024-01-03 23:43 UTC, wackerow requested changes
I think by changing both the capitalization of the intl folder structure AND the `next-i18next.config.js` settings to lowercase everything, we've caused a conflict.

When I load https://deploy-preview-252--ethereum-org-fork.netlify.app/pt-br now, it 404's.
When loading https://deploy-preview-252--ethereum-org-fork.netlify.app/pt-BR it loads the English homepage

---

Updating ONLY the `next-i18next.config.js` to use `load: "currentOnly"`, `cleanCode: true` and `lowerCaseLng: true` produces a result that functions properly. This will automatically capitalize some of the region codes in the URL path, but BOTH forms of capitalization will work.

ie:
- `domain/hy-am` loads to the same, while `domain/hy-AM` redirects to `domain/hy-am`. 
- `domain/pt-br` redirects to `domain/pt-BR`, and `domain/pt-BR` loads to the same
- `domain/zh-tw` loads to the same, while `domain/zh-TW` redirects to `domain/zh-tw`. 

In all of these cases, when testing locally, the correct locale loads, with translations working (even for Portuguese Brazilian which may have `pt-BR` in the path).

When testing on sub-pages, our internal links to something like `domain/pt-br/layer-2` keep the link as-is, but translations still load appropriately. It seems to work regardless of casing, but NOT if we also change the folder structure and `i18n.config.json` `code`  casing

Tested this with `netlify dev` as well, and still works as described.

2024-01-08 13:25 UTC, pettinarip commented
> I think by changing both the capitalization of the intl folder structure AND the `next-i18next.config.js` settings to lowercase everything, we've caused a conflict.
> 
> When I load https://deploy-preview-252--ethereum-org-fork.netlify.app/pt-br now, it 404's. When loading https://deploy-preview-252--ethereum-org-fork.netlify.app/pt-BR it loads the English homepage
> 
> Updating ONLY the `next-i18next.config.js` to use `load: "currentOnly"`, `cleanCode: true` and `lowerCaseLng: true` produces a result that functions properly. This will automatically capitalize some of the region codes in the URL path, but BOTH forms of capitalization will work.
> 
> ie:
> 
> * `domain/hy-am` loads to the same, while `domain/hy-AM` redirects to `domain/hy-am`.
> * `domain/pt-br` redirects to `domain/pt-BR`, and `domain/pt-BR` loads to the same
> * `domain/zh-tw` loads to the same, while `domain/zh-TW` redirects to `domain/zh-tw`.
> 
> In all of these cases, when testing locally, the correct locale loads, with translations working (even for Portuguese Brazilian which may have `pt-BR` in the path).
> 
> When testing on sub-pages, our internal links to something like `domain/pt-br/layer-2` keep the link as-is, but translations still load appropriately. It seems to work regardless of casing, but NOT if we also change the folder structure and `i18n.config.json` `code` casing
> 
> Tested this with `netlify dev` as well, and still works as described.

Nice catch @wackerow. I've pushed a commit and it seems to be working as expected in the preview deploy as well. This config is now the same config we are using in the Gatsby repo, so it should work similarly.

Will keep testing it a bit more.

2024-01-08 16:26 UTC, pettinarip commented
Closing in favor of https://github.com/ethereum/ethereum-org-fork/pull/262

2024-01-08 16:26 UTC, closed without merging